### ISSUE TITLE
Create meta-documentation

### ISSUE THREAD

**Issue by gheber** [HDFGroup/hdf5#1107]
- [x] Describe how to add a reference or a new RFC
- [x] Describe how to add an example
- [x] Describe how to include plain HTML
- [x] Describe how to add an API macro
- [x] Describe the custom commands
- [x] Describe the S3 bucket layout and update routine
- [x] Link the RM template
